services:
  parakeet:
    build: .
    container_name: parakeet-stt
    ports:
      - "8000:8000"
    # env_file: .env               # TODO
    environment:
      LOG_LEVEL: "INFO"
    volumes:
      - ./data/cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
